"bbui": {
        "": {
            "type": "Method"},
        "bb.button.getWidth": {
            "type": "Method"},
        "bb.slider.getWidth": {
            "type": "Method"},
        "bb.scrollPanel.getPeekWidth": {
            "type": "Method"},
        "bb.progress.setMax": {
            "type": "Method"},
        "bb.fileInput.disableGroup": {
            "type": "Method"},
        "bb.actionOverflow.getLeft": {
            "type": "Method"},
        "bb.actionBar.getCaption": {
            "type": "Method"},
        "bb.titleBar.setBackCaption": {
            "type": "Method"},
        "bb.checkbox.enableGroup": {
            "type": "Method"},
        "bb.scrollPanel.onscroll": {
            "type": "Method"},
        "bb.checkbox.setChecked": {
            "type": "Method"},
        "bb.imageList.getLeft": {
            "type": "Method"},
        "bb.radio.getWidth": {
            "type": "Method"},
        "bb.scrollPanel.apply": {
            "type": "Method"},
        "bb.toggle.getOnCaption": {
            "type": "Method"},
        "bb.pillButtons.getButtons": {
            "type": "Method"},
        "bb.bbmBubble.getImage": {
            "type": "Method"},
        "bb.textInput.style": {
            "type": "Method"},
        "bb.toggle.apply": {
            "type": "Method"},
        "bb.scrollPanel.getWidth": {
            "type": "Method"},
        "bb.grid.getWidth": {
            "type": "Method"},
        "bb.dropdown.disable": {
            "type": "Method"},
        "bb.toggle.getWidth": {
            "type": "Method"},
        "bb.actionBar.actionShow": {
            "type": "Method"},
        "bb.titleBar.setActionCaption": {
            "type": "Method"},
        "bb.bbmBubble.apply": {
            "type": "Method"},
        "bb.grid.hid": {
            "type": "Method"},
        "bb.radio.enable": {
            "type": "Method"},
        "bb.progress.apply": {
            "type": "Method"},
        "bb.actionBar.getImage": {
            "type": "Method"},
        "bb.activityIndicator.disableGroup": {
            "type": "Method"},
        "bb.getCurScreen": {
            "type": "Method"},
        "bb.clearScrollers": {
            "type": "Method"},
        "bb.checkbox.getWidth": {
            "type": "Method"},
        "bb.progress.show": {
            "type": "Method"},
        "bb.actionBar.getTabOverflowBtnWidth": {
            "type": "Method"},
        "bb.scrollPanel.show": {
            "type": "Method"},
        "bb.dropdown.hide": {
            "type": "Method"},
        "bb.bbmBubble.getCaption": {
            "type": "Method"},
        "bb.toggle.setChecked": {
            "type": "Method"},
        "bb.pillButtons.show": {
            "type": "Method"},
        "bb.menuBar.overlayTouchHandler": {
            "type": "Method"},
        "bb.dropdown.create": {
            "type": "Method"},
        "bb.toggle.disable": {
            "type": "Method"},
        "bb.radio.getPeekWidth": {
            "type": "Method"},
        "bb.pillButtons.hide": {
            "type": "Method"},
        "bb.roundPanel.disableGroup": {
            "type": "Method"},
        "bb.textInput.resetDot": {
            "type": "Method"},
        "bb.imageList.getAccentText": {
            "type": "Method"},
        "bb.actionOverflow.enableGroup": {
            "type": "Method"},
        "bb.doLoad": {
            "type": "Method"},
        "bb.labelControlContainers.hide": {
            "type": "Method"},
        "bb.textInput.getPeekWidth": {
            "type": "Method"},
        "Function.bind": {
            "type": "Method"},
        "bb.checkbox.getLeft": {
            "type": "Method"},
        "bb.titleBar.getActionCaption": {
            "type": "Method"},
        "bb.activityIndicator.getWidth": {
            "type": "Method"},
        "bb.activityIndicator.getPeekWidth": {
            "type": "Method"},
        "bb.radio.getChecked": {
            "type": "Method"},
        "bb.screen.slideOutLeft": {
            "type": "Method"},
        "bb.init": {
            "type": "Method"},
        "bb.scrollPanel.hide": {
            "type": "Method"},
        "bb.fileInput.getWidth": {
            "type": "Method"},
        "bb.imageList.clear": {
            "type": "Method"},
        "bb.slider.disableGroup": {
            "type": "Method"},
        "bb.bbmBubble.resetDot": {
            "type": "Method"},
        "bb.dropdown.setCaption": {
            "type": "Method"},
        "bb.radio.show": {
            "type": "Method"},
        "bb.fileInput.getLeft": {
            "type": "Method"},
        "bb.bbmBubble.remove": {
            "type": "Method"},
        "bb.removePreviousScreenFromDom": {
            "type": "Method"},
        "bb.radio.setChecked": {
            "type": "Method"},
        "bb.slider.apply": {
            "type": "Method"},
        "bb.roundPanel.apply": {
            "type": "Method"},
        "bb.bbmBubble.getWidth": {
            "type": "Method"},
        "bb.screen.slideOutUp": {
            "type": "Method"},
        "bb.checkbox.show": {
            "type": "Method"},
        "bb.screen.fadeIn": {
            "type": "Method"},
        "bb.actionBar.highlightAction": {
            "type": "Method"},
        "bb.actionBar.hide": {
            "type": "Method"},
        "bb.titleBar.style": {
            "type": "Method"},
        "bb.removeLoadedScripts": {
            "type": "Method"},
        "bb.dropdown.enable": {
            "type": "Method"},
        "bb.bbmBubble.getPeekWidth": {
            "type": "Method"},
        "bb.dropdown.disableGroup": {
            "type": "Method"},
        "bb.slider.getPeekWidth": {
            "type": "Method"},
        "bb.actionBar.setImage": {
            "type": "Method"},
        "bb.pillButtons.disableGroup": {
            "type": "Method"},
        "bb.pillButtons.remove": {
            "type": "Method"},
        "bb.screen.slideOutRight": {
            "type": "Method"},
        "bb.textInput.getLeft": {
            "type": "Method"},
        "bb.imageList.disableGroup": {
            "type": "Method"},
        "bb.screen.slideUp": {
            "type": "Method"},
        "bb.screen.processContext": {
            "type": "Method"},
        "bb.grid.getLeft": {
            "type": "Method"},
        "bb.progress.getWidth": {
            "type": "Method"},
        "bb.scrollPanel.scrollToElement": {
            "type": "Method"},
        "bb.dropdown.show": {
            "type": "Method"},
        "bb.actionOverflow.apply": {
            "type": "Method"},
        "bb.button.apply": {
            "type": "Method"},
        "bb.scrollPanel.remove": {
            "type": "Method"},
        "bb.bbmBubble.setStyle": {
            "type": "Method"},
        "bb.tabOverflow.create": {
            "type": "Method"},
        "bb.loadScreen": {
            "type": "Method"},
        "bb.imageList.style": {
            "type": "Method"},
        "bb.imageList.hide": {
            "type": "Method"},
        "bb.checkbox.hide": {
            "type": "Method"},
        "bb.grid.disableGroup": {
            "type": "Method"},
        "bb.pillButtons.setCaption": {
            "type": "Method"},
        "bb.grid.resetDot": {
            "type": "Method"},
        "bb.radio.hide": {
            "type": "Method"},
        "bb.toggle.getChecked": {
            "type": "Method"},
        "bb.checkbox.apply": {
            "type": "Method"},
        "bb.bbmBubble.show": {
            "type": "Method"},
        "bb.labelControlContainers.resetDot": {
            "type": "Method"},
        "bb.pillButtons.getLeft": {
            "type": "Method"},
        "bb.button.style": {
            "type": "Method"},
        "bb.dropdown.getLeft": {
            "type": "Method"},
        "bb.titleBar.apply": {
            "type": "Method"},
        "bb.actionBar.getActionOverflowBtnWidth": {
            "type": "Method"},
        "bb.dropdown.apply": {
            "type": "Method"},
        "bb.actionBar.setSelectedTab": {
            "type": "Method"},
        "bb.grid.enableGroup": {
            "type": "Method"},
        "bb.radio.remove": {
            "type": "Method"},
        "bb.imageList.appendItem": {
            "type": "Method"},
        "bb.toggle.enable": {
            "type": "Method"},
        "bb.cutHex": {
            "type": "Method"},
        "bb.bbmBubble.getStyle": {
            "type": "Method"},
        "bb.button.disableGroup": {
            "type": "Method"},
        "bb.button.getLeft": {
            "type": "Method"},
        "bb.progress.getLeft": {
            "type": "Method"},
        "bb.progress.setValue": {
            "type": "Method"},
        "bb.radio.disable": {
            "type": "Method"},
        "bb.roundPanel.getLeft": {
            "type": "Method"},
        "bb.imageList.getPeekWidth": {
            "type": "Method"},
        "bb.activityIndicator.style": {
            "type": "Method"},
        "bb.actionOverflow.style": {
            "type": "Method"},
        "bb.labelControlContainers.getPeekWidth": {
            "type": "Method"},
        "bb.bbmBubble.disableGroup": {
            "type": "Method"},
        "bb.radio.getLeft": {
            "type": "Method"},
        "bb.imageList.getDescription": {
            "type": "Method"},
        "bb.progress.setState": {
            "type": "Method"},
        "bb.scrollPanel.resetDot": {
            "type": "Method"},
        "bb.actionBar.apply": {
            "type": "Method"},
        "bb.slider.resetDot": {
            "type": "Method"},
        "bb.bbmBubble.getLeft": {
            "type": "Method"},
        "bb.actionBar.setCaption": {
            "type": "Method"},
        "bb.refresh": {
            "type": "Method"},
        "bb.menuBar.doEndTransition": {
            "type": "Method"},
        "bb.innerWidth": {
            "type": "Method"},
        "bb.checkbox.remove": {
            "type": "Method"},
        "bb.activityIndicator.show": {
            "type": "Method"},
        "bb.fileInput.resetDot": {
            "type": "Method"},
        "bb.innerHeight": {
            "type": "Method"},
        "bb.checkbox.disable": {
            "type": "Method"},
        "bb.roundPanel.style": {
            "type": "Method"},
        "bb.scrollPanel.getLeft": {
            "type": "Method"},
        "bb.button.getPeekWidth": {
            "type": "Method"},
        "bb.checkbox.resetDot": {
            "type": "Method"},
        "bb.labelControlContainers.create": {
            "type": "Method"},
        "bb.guidGenerator": {
            "type": "Method"},
        "bb.progress.disableGroup": {
            "type": "Method"},
        "bb.fileInput.create": {
            "type": "Method"},
        "bb.checkbox.create": {
            "type": "Method"},
        "bb.activityIndicator.remove": {
            "type": "Method"},
        "bb.dropdown.setSelectedItem": {
            "type": "Method"},
        "bb.radio.create": {
            "type": "Method"},
        "bb.scrollPanel.refresh": {
            "type": "Method"},
        "bb.progress.remove": {
            "type": "Method"},
        "bb.textInput.enableGroup": {
            "type": "Method"},
        "bb.toggle.resetDot": {
            "type": "Method"},
        "bb.titleBar.setCaption": {
            "type": "Method"},
        "bb.screen.slideRight": {
            "type": "Method"},
        "bb.bbmBubble.setCaption": {
            "type": "Method"},
        "bb.imageList.remove": {
            "type": "Method"},
        "bb.radio.resetDot": {
            "type": "Method"},
        "bb.grid.getPeekWidth": {
            "type": "Method"},
        "bb.progress.resetDot": {
            "type": "Method"},
        "bb.radio.disableGroup": {
            "type": "Method"},
        "bb.labelControlContainers.remove": {
            "type": "Method"},
        "bb.activityIndicator.create": {
            "type": "Method"},
        "bb.roundPanel.resetDot": {
            "type": "Method"},
        "bb.dropdown.remove": {
            "type": "Method"},
        "bb.button.resetDot": {
            "type": "Method"},
        "bb.pillButtons.resetDot": {
            "type": "Method"},
        "bb.toggle.setOnCaption": {
            "type": "Method"},
        "bb.screen.getMenuBarHeight": {
            "type": "Method"},
        "bb.dropdown.getCaption": {
            "type": "Method"},
        "bb.fileInput.enableGroup": {
            "type": "Method"},
        "bb.actionBar.show": {
            "type": "Method"},
        "bb.pillButtons.getPeekWidth": {
            "type": "Method"},
        "bb.grid.remove": {
            "type": "Method"},
        "bb.activityIndicator.getLeft": {
            "type": "Method"},
        "bb.activityIndicator.apply": {
            "type": "Method"},
        "bb.fileInput.getPeekWidth": {
            "type": "Method"},
        "bb.progress.getPeekWidth": {
            "type": "Method"},
        "bb.imageList.enableGroup": {
            "type": "Method"},
        "bb.checkbox.disableGroup": {
            "type": "Method"},
        "bb.checkbox.getChecked": {
            "type": "Method"},
        "bb.bbmBubble.enableGroup": {
            "type": "Method"},
        "bb.bbmBubble.hide": {
            "type": "Method"},
        "bb.labelControlContainers.disableGroup": {
            "type": "Method"},
        "bb.menuBar.showMenuBar": {
            "type": "Method"},
        "bb.imageList.getItems": {
            "type": "Method"},
        "bb.actionBar.actionHide": {
            "type": "Method"},
        "bb.fileInput.style": {
            "type": "Method"},
        "bb.labelControlContainers.getWidth": {
            "type": "Method"},
        "bb.grid.apply": {
            "type": "Method"},
        "bb.initContainer": {
            "type": "Method"},
        "bb.radio.apply": {
            "type": "Method"},
        "bb.createScreenScroller": {
            "type": "Method"},
        "bb.actionOverflow.getWidth": {
            "type": "Method"},
        "bb.titleBar.onactionclick": {
            "type": "Method"},
        "bb.button.create": {
            "type": "Method"},
        "bb.dropdown.setSelectedText": {
            "type": "Method"},
        "bb.progress.enableGroup": {
            "type": "Method"},
        "bb.slider.setValue": {
            "type": "Method"},
        "bb.pillButtons.getWidth": {
            "type": "Method"},
        "bb.pillButtons.appendButton": {
            "type": "Method"},
        "bb.imageList.insertItemBefore": {
            "type": "Method"},
        "bb.dropdown.refresh": {
            "type": "Method"},
        "bb.roundPanel.getPeekWidth": {
            "type": "Method"},
        "bb.toggle.getOffCaption": {
            "type": "Method"},
        "bb.toggle.show": {
            "type": "Method"},
        "bb.labelControlContainers.style": {
            "type": "Method"},
        "bb.toggle.disableGroup": {
            "type": "Method"},
        "bb.textInput.apply": {
            "type": "Method"},
        "bb.scrollPanel.scrollTo": {
            "type": "Method"},
        "bb.grid.create": {
            "type": "Method"},
        "bb.dropdown.getWidth": {
            "type": "Method"},
        "bb.toggle.enableGroup": {
            "type": "Method"},
        "bb.imageList.getWidth": {
            "type": "Method"},
        "bb.style": {
            "type": "Method"},
        "bb.pillButtons.apply": {
            "type": "Method"},
        "bb.bbmBubble.style": {
            "type": "Method"},
        "bb.titleBar.getAccentText": {
            "type": "Method"},
        "bb.toggle.getPeekWidth": {
            "type": "Method"},
        "bb.toggle.hide": {
            "type": "Method"},
        "bb.progress.hide": {
            "type": "Method"},
        "bb.bbmBubble.setImage": {
            "type": "Method"},
        "bb.actionOverflow.getPeekWidth": {
            "type": "Method"},
        "bb.screen.fadeOut": {
            "type": "Method"},
        "bb.imageList.getImage": {
            "type": "Method"},
        "bb.domready.fire": {
            "type": "Method"},
        "bb.actionOverflow.disableGroup": {
            "type": "Method"},
        "bb.screen.getTitleBarHeight": {
            "type": "Method"},
        "bb.slider.getLeft": {
            "type": "Method"},
        "bb.activityIndicator.hide": {
            "type": "Method"},
        "bb.radio.style": {
            "type": "Method"},
        "bb.titleBar.getCaption": {
            "type": "Method"},
        "bb.bbmBubble.create": {
            "type": "Method"},
        "bb.menuBar.onMenuBarClicked": {
            "type": "Method"},
        "bb.menuBar.hideMenuBar": {
            "type": "Method"},
        "bb.actionBar.unhighlightAction": {
            "type": "Method"},
        "bb.menuBar.apply": {
            "type": "Method"},
        "bb.toggle.getLeft": {
            "type": "Method"},
        "bb.toggle.style": {
            "type": "Method"},
        "bb.roundPanel.getWidth": {
            "type": "Method"},
        "bb.screen.apply": {
            "type": "Method"},
        "bb.pillButtons.enableGroup": {
            "type": "Method"},
        "bb.pushScreen": {
            "type": "Method"},
        "bb.pillButtons.style": {
            "type": "Method"},
        "bb.toggle.setOffCaption": {
            "type": "Method"},
        "bb.slider.create": {
            "type": "Method"},
        "bb.tabOverflow.getWidth": {
            "type": "Method"},
        "bb.domready.fireEventsOnly": {
            "type": "Method"},
        "bb.dropdown.resetDot": {
            "type": "Method"},
        "bb.dropdown.enableGroup": {
            "type": "Method"},
        "bb.radio.enableGroup": {
            "type": "Method"},
        "bb.imageList.apply": {
            "type": "Method"},
        "bb.popScreen": {
            "type": "Method"},
        "bb.radio.isEnabled": {
            "type": "Method"},
        "bb.textInput.create": {
            "type": "Method"},
        "bb.activityIndicator.resetDot": {
            "type": "Method"},
        "bb.checkbox.style": {
            "type": "Method"},
        "bb.getOrientation": {
            "type": "Method"},
        "bb.fileInput.apply": {
            "type": "Method"},
        "bb.scrollPanel.create": {
            "type": "Method"},
        "bb.button.enableGroup": {
            "type": "Method"},
        "bb.checkbox.getPeekWidth": {
            "type": "Method"},
        "bb.actionOverflow.resetDot": {
            "type": "Method"},
        "bb.menuBar.clearMenu": {
            "type": "Method"},
        "bb.slider.style": {
            "type": "Method"},
        "bb.activityIndicator.enableGroup": {
            "type": "Method"},
        "bb.grid.style": {
            "type": "Method"},
        "bb.textInput.disableGroup": {
            "type": "Method"},
        "bb.slider.enableGroup": {
            "type": "Method"},
        "bb.checkbox.enable": {
            "type": "Method"},
        "bb.roundPanel.enableGroup": {
            "type": "Method"},
        "bb.screen.getActionBarHeight": {
            "type": "Method"},
        "bb.labelControlContainers.enableGroup": {
            "type": "Method"},
        "bb.roundPanel.create": {
            "type": "Method"},
        "bb.imageList.create": {
            "type": "Method"},
        "done merging": {
            "type": "Method"},
        "bb.pillButtons.create": {
            "type": "Method"},
        "bb.actionBar.getBackBtnWidth": {
            "type": "Method"},
        "bb.textInput.getWidth": {
            "type": "Method"},
        "bb.screen.slideDown": {
            "type": "Method"},
        "bb.scrollPanel.enableGroup": {
            "type": "Method"},
        "bb.progress.create": {
            "type": "Method"},
        "bb.imageList.show": {
            "type": "Method"},
        "bb.menuBar.createSwipeMenu": {
            "type": "Method"},
        "bb.labelControlContainers.show": {
            "type": "Method"},
        "bb.grid.show": {
            "type": "Method"},
        " ---------------------": {
            "type": "Method"},
        "bb.imageList.resetDot": {
            "type": "Method"},
        "bb.screen.slideOutDown": {
            "type": "Method"},
        "bb.imageList.getTitle": {
            "type": "Method"},
        "bb.toggle.create": {
            "type": "Method"},
        "bb.removeTopMostScreenFromDom": {
            "type": "Method"},
        "bb.dropdown.getPeekWidth": {
            "type": "Method"},
        "bb.pillButtons.getCaption": {
            "type": "Method"},
        "bb.scrollPanel.style": {
            "type": "Method"},
        "bb.scrollPanel.disableGroup": {
            "type": "Method"},
        "bb.bbmBubble.clear": {
            "type": "Method"},
        "bb.actionOverflow.create": {
            "type": "Method"},
        "bb.isScrolledIntoView": {
            "type": "Method"},
        "bb.progress.style": {
            "type": "Method"},
        "bb.titleBar.getBackCaption": {
            "type": "Method"},
        "bb.actionBar.setBackCaption": {
            "type": "Method"},
        "bb.dropdown.style": {
            "type": "Method"},
        "bb.labelControlContainers.apply": {
            "type": "Method"},
        "bb.menuBar.setDimensions": {
            "type": "Method"},
        "bb.screen.slideLeft": {
            "type": "Method"},
        "bb.labelControlContainers.getLeft": {
            "type": "Method"},
        "bb.toggle.remove": {
            "type": "Method"},
        "bb.imageList.refresh": {
            "type": "Method"}}