{
    "cordova": {
        "FileEntry.copyTo": {
            "type": "Method"},
        "splashscreen.show": {
            "type": "Method"},
        "contacts.find": {
            "type": "Method"},
        "FileReader.readAsBinaryString": {
            "type": "Method"},
        "globalization.stringToNumber": {
            "type": "Method"},
        "globalization.stringToDate": {
            "type": "Method"},
        "globalization.getCurrencyPattern": {
            "type": "Method"},
        "media.release": {
            "type": "Method"},
        "accelerometer.watchAcceleration": {
            "type": "Method"},
        "camera.cleanup": {
            "type": "Method"},
        "LocalFileSystem.resolveLocalFileSystemURI": {
            "type": "Method"},
        "geolocation.watchPosition": {
            "type": "Method"},
        "File.slice": {
            "type": "Method"},
        "FileTransfer.upload": {
            "type": "Method"},
        "globalization.getPreferredLanguage": {
            "type": "Method"},
        "FileEntry.toURL": {
            "type": "Method"},
        "media.pause": {
            "type": "Method"},
        "geolocation.clearWatch": {
            "type": "Method"},
        "FileEntry.remove": {
            "type": "Method"},
        "compass.clearWatchFilter": {
            "type": "Method"},
        "localStorage.setIOtem": {
            "type": "Method"},
        "Contact.save": {
            "type": "Method"},
        "media.startRecord": {
            "type": "Method"},
        "accelerometer.getCurrentAcceleration": {
            "type": "Method"},
        "Contact.clone": {
            "type": "Method"},
        "localStorage.getItem": {
            "type": "Method"},
        "DirectoryEntry.moveTo": {
            "type": "Method"},
        "DirectoryEntry.setMetadata": {
            "type": "Method"},
        "FileEntry.file": {
            "type": "Method"},
        "SQLResultSet.rowsAffected": {
            "type": "Method"},
        "media.getCurrentPosition": {
            "type": "Method"},
        "MediaFile.getFormatData": {
            "type": "Method"},
        "globalization.dateToString": {
            "type": "Method"},
        "SQLResultSet.insertId": {
            "type": "Method"},
        "media.stop": {
            "type": "Method"},
        "localStorage.clear": {
            "type": "Method"},
        "localStorage.removeItem": {
            "type": "Method"},
        "DirectoryEntry.createReader": {
            "type": "Method"},
        "FileReader.abort": {
            "type": "Method"},
        "contacts.create": {
            "type": "Method"},
        "Contact.remove": {
            "type": "Method"},
        "InAppBrowser.show": {
            "type": "Method"},
        "SQLResultSetRowList.item": {
            "type": "Method"},
        "InAppBrowser.removeEventListener": {
            "type": "Method"},
        "InAppBrowser.close": {
            "type": "Method"},
        "FileEntry.getParent": {
            "type": "Method"},
        "FileEntry.getMetadata": {
            "type": "Method"},
        "compass.watchHeadingFilter": {
            "type": "Method"},
        "notification.vibrate": {
            "type": "Method"},
        "globalization.getDateNames": {
            "type": "Method"},
        "globalization.isDayLightSavingsTime": {
            "type": "Method"},
        "compass.watchHeading": {
            "type": "Method"},
        "Database.changeVersion": {
            "type": "Method"},
        "globalization.getLocaleName": {
            "type": "Method"},
        "splashscreen.hide": {
            "type": "Method"},
        "DirectoryEntry.getFile": {
            "type": "Method"},
        "DirectoryEntry.getParent": {
            "type": "Method"},
        "Stroage.openDatabase": {
            "type": "Method"},
        "globalization.numberToString": {
            "type": "Method"},
        "DirectoryEntry.remove": {
            "type": "Method"},
        "FileTransfer.abort": {
            "type": "Method"},
        "compass.getCurrentHeading": {
            "type": "Method"},
        "SQLResultSet.rows": {
            "type": "Method"},
        "InAppBrowser.insertCSS": {
            "type": "Method"},
        "FileReader.readAsText": {
            "type": "Method"},
        "media.play": {
            "type": "Method"},
        "media.stopRecord": {
            "type": "Method"},
        "localStorage.key": {
            "type": "Method"},
        "accelerometer.clearWatch": {
            "type": "Method"},
        "InAppBrowser.executeScript": {
            "type": "Method"},
        "InAppBrowser.addEventListener": {
            "type": "Method"},
        "notification.prompt": {
            "type": "Method"},
        "DirectoryEntry.toURL": {
            "type": "Method"},
        "notification.beep": {
            "type": "Method"},
        "FileReader.readAsArrayBuffer": {
            "type": "Method"},
        "capture.captureImage": {
            "type": "Method"},
        "DirectoryEntry.removeRecursively": {
            "type": "Method"},
        "FileEntry.createWriter": {
            "type": "Method"},
        "capture.captureVideo": {
            "type": "Method"},
        "globalization.getDatePattern": {
            "type": "Method"},
        "DirectoryReader.readEntries": {
            "type": "Method"},
        "media.seekTo": {
            "type": "Method"},
        "FileTransfer.download": {
            "type": "Method"},
        "FileEntry.setMetadata": {
            "type": "Method"},
        "DirectoryEntry.copyTo": {
            "type": "Method"},
        "SQLTransaction.executeSQL": {
            "type": "Method"},
        "FileEntry.moveTo": {
            "type": "Method"},
        "notification.alert": {
            "type": "Method"},
        "FileReader.readAsDataURL": {
            "type": "Method"},
        "geolocation.getCurrentPosition": {
            "type": "Method"},
        "LocalFileSystem.requestFileSystem": {
            "type": "Method"},
        "camera.getPicture": {
            "type": "Method"},
        "media.getDuration": {
            "type": "Method"},
        "media.setVolume": {
            "type": "Method"},
        "notification.confirm": {
            "type": "Method"},
        "DirectoryEntry.getDirectory": {
            "type": "Method"},
        "Database.transaction": {
            "type": "Method"},
        "globalization.getNumberPattern": {
            "type": "Method"},
        "compass.clearWatch": {
            "type": "Method"},
        "DirectoryEntry.getMetadata": {
            "type": "Method"},
        "globalization.getFirstDayOfWeek": {
            "type": "Method"},
        "capture.captureAudio": {
            "type": "Method"}}}
