{
    "ember": {
        "Ember.LinkView.init": {
            "type": "Method"},
        "Ember.Observable.getProperties": {
            "type": "Method"},
        "Ember.Comparable.compare": {
            "type": "Method"},
        "Ember.ControllerMixin.makeToString": {
            "type": "Method"},
        "String.classify": {
            "type": "Method"},
        "Ember.Handlebars.helpers.input": {
            "type": "Method"},
        "Ember.Handlebars.helpers.connectOutlet": {
            "type": "Method"},
        "Ember.ArrayProxy.objectAtContent": {
            "type": "Method"},
        "Ember.Map.remove": {
            "type": "Method"},
        "Ember.Observable.cacheFor": {
            "type": "Method"},
        "Ember.Evented.has": {
            "type": "Method"},
        "Ember.View.didInsertElement": {
            "type": "Method"},
        "Ember.CoreObject.create": {
            "type": "Method"},
        "Ember.MutableEnumerable.removeObjects": {
            "type": "Method"},
        "Ember.ObjectController.set": {
            "type": "Method"},
        "Ember.Route.setupController": {
            "type": "Method"},
        "Ember.View.willInsertElement": {
            "type": "Method"},
        "Ember.ComputedProperty.property": {
            "type": "Method"},
        "String.camelize": {
            "type": "Method"},
        "String.decamelize": {
            "type": "Method"},
        "Ember.Application.inject": {
            "type": "Method"},
        "Ember.Evented.one": {
            "type": "Method"},
        "Ember.View.findElementInParentElement": {
            "type": "Method"},
        "Ember.CoreObject.eachComputedProperty": {
            "type": "Method"},
        "Ember.Logger.info": {
            "type": "Method"},
        "Ember.Handlebars.helpers.partial": {
            "type": "Method"},
        "Ember.Handlebars.helpers.bind-attr": {
            "type": "Method"},
        "Ember.MapWithDefault.get": {
            "type": "Method"},
        "Ember.Test.registerHelper": {
            "type": "Method"},
        "Ember.Observable.getWithDefault": {
            "type": "Method"},
        "Ember.ControllerMixin.reset": {
            "type": "Method"},
        "Ember.OrderedSet.remove": {
            "type": "Method"},
        "Ember.Test.unregisterHelper": {
            "type": "Method"},
        "Ember.DefaultResolver.resolve": {
            "type": "Method"},
        "Ember.Binding.copy": {
            "type": "Method"},
        "Ember.ControllerMixin.set": {
            "type": "Method"},
        "Ember.Logger.error": {
            "type": "Method"},
        "Ember.TextSupport.insertNewLine": {
            "type": "Method"},
        "Ember.TrackedArray.apply": {
            "type": "Method"},
        "Ember.CoreObject.init": {
            "type": "Method"},
        "Ember.MutableArray.unshiftObject": {
            "type": "Method"},
        "Ember.Test.wait": {
            "type": "Method"},
        "String.dasherize": {
            "type": "Method"},
        "Ember.Component.sendAction": {
            "type": "Method"},
        "Ember.ComputedProperty.meta": {
            "type": "Method"},
        "Ember.Handlebars.helpers.disconnectOutlet": {
            "type": "Method"},
        "Ember.CoreObject.metaForProperty": {
            "type": "Method"},
        "Ember.View.removeChild": {
            "type": "Method"},
        "Ember.MutableEnumerable.removeObject": {
            "type": "Method"},
        "Ember.ArrayController.lookupItemController": {
            "type": "Method"},
        "Ember.OrderedSet.add": {
            "type": "Method"},
        "Ember.Route.send": {
            "type": "Method"},
        "Ember.Logger.log": {
            "type": "Method"},
        "Ember.ControllerMixin.destroy": {
            "type": "Method"},
        "String.fmt": {
            "type": "Method"},
        "Ember.Route.model": {
            "type": "Method"},
        "Ember.MutableArray.unshiftObjects": {
            "type": "Method"},
        "Ember.MutableArray.clear": {
            "type": "Method"},
        "Ember.ComputedProperty.cacheable": {
            "type": "Method"},
        "Ember.MutableArray.setObjects": {
            "type": "Method"},
        "Ember.Test.onInjectHelpers": {
            "type": "Method"},
        "Ember.MutableArray.reverseObjects": {
            "type": "Method"},
        "Ember.Route.disconnectOutlet": {
            "type": "Method"},
        "Ember.OrderedSet.has": {
            "type": "Method"},
        "Ember.ControllerMixin.replaceRoute": {
            "type": "Method"},
        "Ember.View.createChildView": {
            "type": "Method"},
        "Ember.Handlebars.helpers.if": {
            "type": "Method"},
        "Ember.Handlebars.helpers.init": {
            "type": "Method"},
        "Ember.TrackedArray.removeItems": {
            "type": "Method"},
        "Ember.Enumerable.contains": {
            "type": "Method"},
        "Ember.Handlebars.helpers.log": {
            "type": "Method"},
        "Ember.Copyable.frozenCopy": {
            "type": "Method"},
        "Ember.Observable.notifyPropertyChange": {
            "type": "Method"},
        "Ember.Enumerable.reduce": {
            "type": "Method"},
        "Ember.Handlebars.helpers.loc": {
            "type": "Method"},
        "Ember.Controller.destroy": {
            "type": "Method"},
        "Ember.Array.arrayContentDidChange": {
            "type": "Method"},
        "Ember.View.appendTo": {
            "type": "Method"},
        "Ember.MutableArray.replace": {
            "type": "Method"},
        "String.capitalize": {
            "type": "Method"},
        "Ember.Route.deactivate": {
            "type": "Method"},
        "Ember.RenderBuffer.addClass": {
            "type": "Method"},
        "Function.property": {
            "type": "Method"},
        "Ember.Route.replaceWith": {
            "type": "Method"},
        "String.loc": {
            "type": "Method"},
        "Ember.Enumerable.mapBy": {
            "type": "Method"},
        "Function.observesImmediately": {
            "type": "Method"},
        "Ember.Array.slice": {
            "type": "Method"},
        "Ember.Observable.endPropertyChanges": {
            "type": "Method"},
        "Ember.Set.push": {
            "type": "Method"},
        "Ember.Enumerable.removeEnumerableObserver": {
            "type": "Method"},
        "Ember.Test.promise": {
            "type": "Method"},
        "Ember.Mixin.detect": {
            "type": "Method"},
        "Ember.View.render": {
            "type": "Method"},
        "Ember.RenderBuffer.removeAttr": {
            "type": "Method"},
        "Ember.ControllerMixin.factoryInjection": {
            "type": "Method"},
        "Ember.Enumerable.filter": {
            "type": "Method"},
        "Ember.Set.add": {
            "type": "Method"},
        "Ember.Set.clear": {
            "type": "Method"},
        "Ember.Map.copy": {
            "type": "Method"},
        "Ember.Array.objectAt": {
            "type": "Method"},
        "Ember.View.parentViewDidChange": {
            "type": "Method"},
        "Ember.RenderBuffer.id": {
            "type": "Method"},
        "Ember.NativeArray.activate": {
            "type": "Method"},
        "Ember.TrackedArray.addItems": {
            "type": "Method"},
        "Ember.Enumerable.without": {
            "type": "Method"},
        "Ember.Set.shift": {
            "type": "Method"},
        "Ember.ObjectController.get": {
            "type": "Method"},
        "String.underscore": {
            "type": "Method"},
        "Ember.ArrayController.set": {
            "type": "Method"},
        "Ember.View.removeFromParent": {
            "type": "Method"},
        "Ember.RenderBuffer.push": {
            "type": "Method"},
        "Ember.Freezable.freeze": {
            "type": "Method"},
        "Ember.View.replaceIn": {
            "type": "Method"},
        "Ember.CoreObject.willDestroy": {
            "type": "Method"},
        "Ember.Test.click": {
            "type": "Method"},
        "Ember.CoreObject.toString": {
            "type": "Method"},
        "Ember.Route.modelFor": {
            "type": "Method"},
        "Ember.Map.has": {
            "type": "Method"},
        "Ember.CollectionView.arrayWillChange": {
            "type": "Method"},
        "Ember.Enumerable.rejectBy": {
            "type": "Method"},
        "Ember.MapWithDefault.copy": {
            "type": "Method"},
        "Ember.Controller.get": {
            "type": "Method"},
        "Ember.Application.register": {
            "type": "Method"},
        "Ember.Observable.get": {
            "type": "Method"},
        "Ember.TextSupport.focusIn": {
            "type": "Method"},
        "Ember.ComputedProperty.set": {
            "type": "Method"},
        "Ember.ControllerMixin.has": {
            "type": "Method"},
        "Ember.View.removeAllChildren": {
            "type": "Method"},
        "Ember.Route.controllerFor": {
            "type": "Method"},
        "Ember.Handlebars.helpers.unless": {
            "type": "Method"},
        "Ember.TextSupport.focusOut": {
            "type": "Method"},
        "Ember.ArrayController.get": {
            "type": "Method"},
        "Ember.Map.get": {
            "type": "Method"},
        "Ember.OrderedSet.copy": {
            "type": "Method"},
        "Ember.Array.addArrayObserver": {
            "type": "Method"},
        "Ember.Array.lastIndexOf": {
            "type": "Method"},
        "Function.on": {
            "type": "Method"},
        "Ember.Handlebars.get": {
            "type": "Method"},
        "Ember.Observable.hasObserverFor": {
            "type": "Method"},
        "Ember.Enumerable.getEach": {
            "type": "Method"},
        "Ember.Enumerable.uniq": {
            "type": "Method"},
        "Ember.Application.reset": {
            "type": "Method"},
        "Ember.Evented.on": {
            "type": "Method"},
        "Ember.View.append": {
            "type": "Method"},
        "Ember.Set.addEach": {
            "type": "Method"},
        "Ember.Observable.beginPropertyChanges": {
            "type": "Method"},
        "Ember.TextSupport.cancel": {
            "type": "Method"},
        "Ember.Binding.to": {
            "type": "Method"},
        "Ember.Handlebars.registerBoundHelper": {
            "type": "Method"},
        "Ember.ArrayController.destroy": {
            "type": "Method"},
        "Ember.View.destroyElement": {
            "type": "Method"},
        "Ember.Enumerable.every": {
            "type": "Method"},
        "Ember.ControllerMixin.transitionToRoute": {
            "type": "Method"},
        "Ember.LinkView.click": {
            "type": "Method"},
        "Ember.OrderedSet.toArray": {
            "type": "Method"},
        "Ember.Evented.trigger": {
            "type": "Method"},
        "Ember.Test.visit": {
            "type": "Method"},
        "Ember.Observable.propertyDidChange": {
            "type": "Method"},
        "Ember.Observable.decrementProperty": {
            "type": "Method"},
        "Ember.Deferred.resolve": {
            "type": "Method"},
        "Ember.Enumerable.toArray": {
            "type": "Method"},
        "Ember.Route.store": {
            "type": "Method"},
        "Ember.Observable.toggleProperty": {
            "type": "Method"},
        "Ember.ComputedProperty.volatile": {
            "type": "Method"},
        "Ember.Enumerable.invoke": {
            "type": "Method"},
        "Ember.Application.advanceReadiness": {
            "type": "Method"},
        "Ember.Route.afterModel": {
            "type": "Method"},
        "Ember.Handlebars.helpers.view": {
            "type": "Method"},
        "Ember.Observable.addObserver": {
            "type": "Method"},
        "Ember.Test.setupForTesting": {
            "type": "Method"},
        "Ember.CollectionView.init": {
            "type": "Method"},
        "Ember.Handlebars.helpers.yield": {
            "type": "Method"},
        "Ember.View.destroy": {
            "type": "Method"},
        "Ember.Enumerable.find": {
            "type": "Method"},
        "Ember.MutableArray.shiftObject": {
            "type": "Method"},
        "Ember.Set.pop": {
            "type": "Method"},
        "Ember.Deferred.then": {
            "type": "Method"},
        "Ember.Handlebars.helpers.outlet": {
            "type": "Method"},
        "Ember.Binding.disconnect": {
            "type": "Method"},
        "Function.observesBefore": {
            "type": "Method"},
        "Ember.Mixin.reopen": {
            "type": "Method"},
        "Ember.View.createElement": {
            "type": "Method"},
        "Ember.Evented.off": {
            "type": "Method"},
        "Ember.Test.keyEvent": {
            "type": "Method"},
        "Ember.ArrayProxy.replaceContent": {
            "type": "Method"},
        "Ember.Handlebars.helpers.each": {
            "type": "Method"},
        "Ember.Test.fillIn": {
            "type": "Method"},
        "Ember.Binding.oneWay": {
            "type": "Method"},
        "Ember.Binding.connect": {
            "type": "Method"},
        "Ember.Observable.removeObserver": {
            "type": "Method"},
        "Ember.Handlebars.helpers.render": {
            "type": "Method"},
        "Ember.ControllerMixin.unregister": {
            "type": "Method"},
        "Ember.Deferred.reject": {
            "type": "Method"},
        "Ember.CollectionView.destroy": {
            "type": "Method"},
        "Ember.ComputedProperty.readOnly": {
            "type": "Method"},
        "Ember.Handlebars.helpers.control": {
            "type": "Method"},
        "Ember.ComputedProperty.get": {
            "type": "Method"},
        "Ember.Handlebars.helper": {
            "type": "Method"},
        "Ember.Route.activate": {
            "type": "Method"},
        "Ember.Array.indexOf": {
            "type": "Method"},
        "Ember.Set.unshift": {
            "type": "Method"},
        "Ember.Observable.set": {
            "type": "Method"},
        "Ember.Enumerable.enumerableContentDidChange": {
            "type": "Method"},
        "Ember.Array.removeArrayObserver": {
            "type": "Method"},
        "Ember.Controller.set": {
            "type": "Method"},
        "Ember.Logger.assert": {
            "type": "Method"},
        "Ember.MutableArray.insertAt": {
            "type": "Method"},
        "Ember.RenderBuffer.string": {
            "type": "Method"},
        "Ember.Enumerable.addEnumerableObserver": {
            "type": "Method"},
        "Ember.Test.injectTestHelpers": {
            "type": "Method"},
        "Ember.RenderBuffer.attr": {
            "type": "Method"},
        "Ember.MutableArray.pushObject": {
            "type": "Method"},
        "Ember.SubArray.addItem": {
            "type": "Method"},
        "Ember.CoreObject.reopenClass": {
            "type": "Method"},
        "Ember.Set.removeEach": {
            "type": "Method"},
        "Ember.Array.arrayContentWillChange": {
            "type": "Method"},
        "Ember.CoreObject.reopen": {
            "type": "Method"},
        "Ember.ControllerMixin.resolve": {
            "type": "Method"},
        "Ember.RenderBuffer.prop": {
            "type": "Method"},
        "Ember.Application.deferReadiness": {
            "type": "Method"},
        "Ember.Enumerable.setEach": {
            "type": "Method"},
        "Ember.MutableEnumerable.addObject": {
            "type": "Method"},
        "Ember.MutableArray.popObject": {
            "type": "Method"},
        "Ember.TestAdapter.asyncStart": {
            "type": "Method"},
        "Ember.ControllerMixin.get": {
            "type": "Method"},
        "Ember.Handlebars.helpers.action": {
            "type": "Method"},
        "Ember.Set.remove": {
            "type": "Method"},
        "Ember.OrderedSet.clear": {
            "type": "Method"},
        "Ember.Application.ready": {
            "type": "Method"},
        "String.w": {
            "type": "Method"},
        "Ember.Mixin.apply": {
            "type": "Method"},
        "Ember.Test.find": {
            "type": "Method"},
        "Ember.Route.serialize": {
            "type": "Method"},
        "Ember.ControllerMixin.describe": {
            "type": "Method"},
        "Ember.Binding.toString": {
            "type": "Method"},
        "Ember.Enumerable.reject": {
            "type": "Method"},
        "Ember.MutableArray.pushObjects": {
            "type": "Method"},
        "Ember.Handlebars.helpers.with": {
            "type": "Method"},
        "Ember._HandlebarsBoundView.render": {
            "type": "Method"},
        "Ember.Handlebars.helpers.textarea": {
            "type": "Method"},
        "Ember.Logger.debug": {
            "type": "Method"},
        "Ember.TextSupport.keyPress": {
            "type": "Method"},
        "Ember.Observable.propertyWillChange": {
            "type": "Method"},
        "Ember.TestAdapter.exception": {
            "type": "Method"},
        "Ember.ControllerMixin.child": {
            "type": "Method"},
        "Ember.Enumerable.enumerableContentWillChange": {
            "type": "Method"},
        "Ember.Enumerable.map": {
            "type": "Method"},
        "Ember.Enumerable.compact": {
            "type": "Method"},
        "Ember.ControllerMixin.normalize": {
            "type": "Method"},
        "Ember.ControllerMixin.lookupFactory": {
            "type": "Method"},
        "Function.observes": {
            "type": "Method"},
        "Ember.Handlebars.compile": {
            "type": "Method"},
        "Ember.Route.findModel": {
            "type": "Method"},
        "Ember.Route.renderTemplate": {
            "type": "Method"},
        "Ember.CoreObject.createWithMixins": {
            "type": "Method"},
        "Ember.Handlebars.helpers.debugger": {
            "type": "Method"},
        "Ember.Enumerable.filterBy": {
            "type": "Method"},
        "Ember.View.willClearRender": {
            "type": "Method"},
        "Ember.Observable.setProperties": {
            "type": "Method"},
        "Ember.ControllerMixin.lookup": {
            "type": "Method"},
        "Ember.MapWithDefault.create": {
            "type": "Method"},
        "Ember.ControllerMixin.register": {
            "type": "Method"},
        "Ember.Handlebars.precompile": {
            "type": "Method"},
        "Ember.View.remove": {
            "type": "Method"},
        "Ember.CollectionView.arrayDidChange": {
            "type": "Method"},
        "Ember.TargetActionSupport.triggerAction": {
            "type": "Method"},
        "Ember.RenderBuffer.element": {
            "type": "Method"},
        "Ember.EachProxy.unknownProperty": {
            "type": "Method"},
        "Ember.OrderedSet.forEach": {
            "type": "Method"},
        "Ember.Enumerable.any": {
            "type": "Method"},
        "Ember.Enumerable.everyBy": {
            "type": "Method"},
        "Ember.Map.forEach": {
            "type": "Method"},
        "Ember.Map.set": {
            "type": "Method"},
        "Ember.Enumerable.nextObject": {
            "type": "Method"},
        "Ember.Route.render": {
            "type": "Method"},
        "Ember.CoreObject.destroy": {
            "type": "Method"},
        "Ember.CollectionView.createChildView": {
            "type": "Method"},
        "Ember.Route.transitionTo": {
            "type": "Method"},
        "Ember.ObjectController.destroy": {
            "type": "Method"},
        "Ember.Route.beforeModel": {
            "type": "Method"},
        "Ember.MutableEnumerable.addObjects": {
            "type": "Method"},
        "Ember.ControllerMixin.optionsForType": {
            "type": "Method"},
        "Ember.ControllerMixin.remove": {
            "type": "Method"},
        "Ember.Test.removeTestHelpers": {
            "type": "Method"},
        "Ember.RenderBuffer.removeProp": {
            "type": "Method"},
        "Ember.Handlebars.helpers.unbound": {
            "type": "Method"},
        "Ember.Set.isEqual": {
            "type": "Method"},
        "Ember.Enumerable.findBy": {
            "type": "Method"},
        "Ember.Mixin.create": {
            "type": "Method"},
        "Ember.ControllerMixin.injection": {
            "type": "Method"},
        "Ember.TestAdapter.asyncEnd": {
            "type": "Method"},
        "Ember.Logger.warn": {
            "type": "Method"},
        "Ember.Handlebars.helpers.link-to": {
            "type": "Method"},
        "Ember.ControllerMixin.eachLocal": {
            "type": "Method"},
        "Ember.Array.objectsAt": {
            "type": "Method"},
        "Ember.Enumerable.anyBy": {
            "type": "Method"},
        "Ember.Enumerable.forEach": {
            "type": "Method"},
        "String.htmlSafe": {
            "type": "Method"},
        "Ember.Route.generateController": {
            "type": "Method"},
        "Ember.Map.create": {
            "type": "Method"},
        "Ember.SubArray.removeItem": {
            "type": "Method"},
        "Ember.Observable.incrementProperty": {
            "type": "Method"},
        "Ember.Binding.from": {
            "type": "Method"},
        "Ember.ControllerMixin.options": {
            "type": "Method"},
        "Ember.View.willDestroyElement": {
            "type": "Method"},
        "Ember.RenderBuffer.style": {
            "type": "Method"},
        "Ember.OrderedSet.isEmpty": {
            "type": "Method"},
        "Ember.Test.findWithAssert": {
            "type": "Method"},
        "Ember.OrderedSet.create": {
            "type": "Method"},
        "Ember.MutableArray.removeAt": {
            "type": "Method"},
        "Ember.Copyable.copy": {
            "type": "Method"},
        "Ember.View.rerender": {
            "type": "Method"}}}
