{
    "jQuery": {
        "deferred.resolveWith": {
            "type": "Method"},
        "deferred.progress": {
            "type": "Method"},
        "callbacks.add": {
            "type": "Method"},
        "jQuery.trigger": {
            "type": "Method"},
        "jQuery.andSelf": {
            "type": "Method"},
        "jQuery.insertAfter": {
            "type": "Method"},
        "jQuery.toArray": {
            "type": "Method"},
        "deferred.promise": {
            "type": "Method"},
        "event.metaKey": {
            "type": "EventObject"},
        "jQuery.val": {
            "type": "Method"},
        "jQuery.contents": {
            "type": "Method"},
        "jQuery.nextUntil": {
            "type": "Method"},
        "callbacks.fireWith": {
            "type": "Method"},
        "jQuery.data": [
            {
                "type": "Method"},
            {
                "type": "Method"}],
        "jQuery.fx.off": {
            "type": "Method"},
        "jQuery.hasData": {
            "type": "Method"},
        "jQuery.error": [
            {
                "type": "Method"},
            {
                "type": "Method"}],
        "jQuery.hasClass": {
            "type": "Method"},
        "jQuery.delegate": {
            "type": "Method"},
        "jQuery.Callbacks": {
            "type": "Method"},
        "deferred.then": {
            "type": "Method"},
        "jQuery.keyup": {
            "type": "Method"},
        "event.isPropagationStopped": {
            "type": "Method"},
        "jQuery.blur": {
            "type": "Method"},
        "jQuery.isEmptyObject": {
            "type": "Method"},
        "callbacks.disable": {
            "type": "Method"},
        "jQuery.remove": {
            "type": "Method"},
        "deferred.rejectWith": {
            "type": "Method"},
        "jQuery.fadeIn": {
            "type": "Method"},
        "jQuery.resize": {
            "type": "Method"},
        "jQuery.get": [
            {
                "type": "Method"},
            {
                "type": "Method"}],
        "jQuery.ajaxTransport": {
            "type": "Method"},
        "jQuery.makeArray": {
            "type": "Method"},
        "jQuery.each": [
            {
                "type": "Method"},
            {
                "type": "Method"}],
        "jQuery.length": {
            "type": "Method"},
        "jQuery.next": {
            "type": "Method"},
        "event.namespace": {
            "type": "EventObject"},
        "event.target": {
            "type": "EventObject"},
        "callbacks.lock": {
            "type": "Method"},
        "jQuery.addClass": {
            "type": "Method"},
        "jQuery.merge": {
            "type": "Method"},
        "jQuery.prop": {
            "type": "Method"},
        "jQuery.add": {
            "type": "Method"},
        "jQuery.support": {
            "type": "Method"},
        "jQuery.on": {
            "type": "Method"},
        "jQuery.unload": {
            "type": "Method"},
        "jQuery.removeAttr": {
            "type": "Method"},
        "jQuery.wrap": {
            "type": "Method"},
        "jQuery.contains": {
            "type": "Method"},
        "jQuery.promise": {
            "type": "Method"},
        "jQuery.html": {
            "type": "Method"},
        "deferred.notifyWith": {
            "type": "Method"},
        "jQuery.context": {
            "type": "Method"},
        "event.stopImmediatePropagation": {
            "type": "Method"},
        "jQuery.Deferred": {
            "type": "Method"},
        "event.type": {
            "type": "EventObject"},
        "event.relatedTarget": {
            "type": "EventObject"},
        "jQuery.nextAll": {
            "type": "Method"},
        "jQuery.offset": {
            "type": "Method"},
        "jQuery.scroll": {
            "type": "Method"},
        "event.preventDefault": {
            "type": "Method"},
        "jQuery.css": {
            "type": "Method"},
        "jQuery.first": {
            "type": "Method"},
        "jQuery.ajaxSuccess": {
            "type": "Method"},
        "jQuery.bind": {
            "type": "Method"},
        "jQuery.noop": {
            "type": "Method"},
        "jQuery.type": {
            "type": "Method"},
        "jQuery.mousemove": {
            "type": "Method"},
        "jQuery.appendTo": {
            "type": "Method"},
        "jQuery.hide": {
            "type": "Method"},
        "jQuery.holdReady": {
            "type": "Method"},
        "jQuery.wrapAll": {
            "type": "Method"},
        "jQuery.parseXML": {
            "type": "Method"},
        "jQuery.addBack": {
            "type": "Method"},
        "jQuery.innerHeight": {
            "type": "Method"},
        "jQuery.index": {
            "type": "Method"},
        "jQuery.height": {
            "type": "Method"},
        "jQuery.trim": {
            "type": "Method"},
        "jQuery.cssHooks": {
            "type": "Method"},
        "event.result": {
            "type": "EventObject"},
        "jQuery.show": {
            "type": "Method"},
        "jQuery.removeData": [
            {
                "type": "Method"},
            {
                "type": "Method"}],
        "jQuery.ajaxError": {
            "type": "Method"},
        "jQuery.parseJSON": {
            "type": "Method"},
        "callbacks.empty": {
            "type": "Method"},
        "jQuery.prev": {
            "type": "Method"},
        "jQuery.has": {
            "type": "Method"},
        "event.currentTarget": {
            "type": "EventObject"},
        "jQuery.change": {
            "type": "Method"},
        "jQuery.keypress": {
            "type": "Method"},
        "jQuery.parentsUntil": {
            "type": "Method"},
        "jQuery.dblclick": {
            "type": "Method"},
        "jQuery.selector": {
            "type": "Method"},
        "jQuery.text": {
            "type": "Method"},
        "jQuery.width": {
            "type": "Method"},
        "jQuery.fadeToggle": {
            "type": "Method"},
        "deferred.reject": {
            "type": "Method"},
        "jQuery.grep": {
            "type": "Method"},
        "jQuery.before": {
            "type": "Method"},
        "jQuery.getJSON": {
            "type": "Method"},
        "jQuery.inArray": {
            "type": "Method"},
        "jQuery.focusout": {
            "type": "Method"},
        "jQuery.boxModel": {
            "type": "Method"},
        "jQuery.stop": {
            "type": "Method"},
        "jQuery.animate": {
            "type": "Method"},
        "jQuery.ajaxStart": {
            "type": "Method"},
        "jQuery.fadeOut": {
            "type": "Method"},
        "jQuery.live": {
            "type": "Method"},
        "jQuery.mouseout": {
            "type": "Method"},
        "jQuery.fx.interval": {
            "type": "Method"},
        "jQuery.select": {
            "type": "Method"},
        "jQuery.removeClass": {
            "type": "Method"},
        "jQuery.outerHeight": {
            "type": "Method"},
        "jQuery.unique": {
            "type": "Method"},
        "callbacks.remove": {
            "type": "Method"},
        "jQuery.one": {
            "type": "Method"},
        "jQuery.ajaxSend": {
            "type": "Method"},
        "jQuery.detach": {
            "type": "Method"},
        "jQuery.innerWidth": {
            "type": "Method"},
        "jQuery.fn.extend": {
            "type": "Method"},
        "jQuery.append": {
            "type": "Method"},
        "jQuery.extend": {
            "type": "Method"},
        "jQuery.when": {
            "type": "Method"},
        "deferred.isRejected": {
            "type": "Method"},
        "event.which": {
            "type": "EventObject"},
        "callbacks.locked": {
            "type": "Method"},
        "jQuery.slice": {
            "type": "Method"},
        "jQuery.serialize": {
            "type": "Method"},
        "jQuery.isXMLDoc": {
            "type": "Method"},
        "deferred.pipe": {
            "type": "Method"},
        "jQuery.focusin": {
            "type": "Method"},
        "jQuery.eq": {
            "type": "Method"},
        "jQuery.outerWidth": {
            "type": "Method"},
        "jQuery.parseHTML": {
            "type": "Method"},
        "jQuery.last": {
            "type": "Method"},
        "jQuery.isWindow": {
            "type": "Method"},
        "deferred.done": {
            "type": "Method"},
        "jQuery.ajaxPrefilter": {
            "type": "Method"},
        "jQuery.die": {
            "type": "Method"},
        "jQuery.clone": {
            "type": "Method"},
        "jQuery.queue": [
            {
                "type": "Method"},
            {
                "type": "Method"}],
        "jQuery.isArray": {
            "type": "Method"},
        "jQuery.toggle": [
            {
                "type": "Method"},
            {
                "type": "Method"}],
        "jQuery.end": {
            "type": "Method"},
        "deferred.state": {
            "type": "Method"},
        "deferred.fail": {
            "type": "Method"},
        "jQuery.browser": {
            "type": "Method"},
        "jQuery.clearQueue": {
            "type": "Method"},
        "jQuery.parents": {
            "type": "Method"},
        "jQuery.scrollLeft": {
            "type": "Method"},
        "jQuery.load": [
            {
                "type": "Method"},
            {
                "type": "Method"}],
        "event.delegateTarget": {
            "type": "EventObject"},
        "jQuery": {
            "type": "Method"},
        "jQuery.now": {
            "type": "Method"},
        "jQuery.mouseup": {
            "type": "Method"},
        "jQuery.not": {
            "type": "Method"},
        "jQuery.getScript": {
            "type": "Method"},
        "jQuery.pushStack": {
            "type": "Method"},
        "event.isImmediatePropagationStopped": {
            "type": "Method"},
        "jQuery.keydown": {
            "type": "Method"},
        "jQuery.mousedown": {
            "type": "Method"},
        "jQuery.noConflict": {
            "type": "Method"},
        "jQuery.unbind": {
            "type": "Method"},
        "jQuery.ajax": {
            "type": "Method"},
        "jQuery.globalEval": {
            "type": "Method"},
        "jQuery.offsetParent": {
            "type": "Method"},
        "jQuery.after": {
            "type": "Method"},
        "jQuery.toggleClass": {
            "type": "Method"},
        "callbacks.fired": {
            "type": "Method"},
        "jQuery.slideUp": {
            "type": "Method"},
        "jQuery.isNumeric": {
            "type": "Method"},
        "jQuery.empty": {
            "type": "Method"},
        "jQuery.jquery": {
            "type": "Method"},
        "jQuery.scrollTop": {
            "type": "Method"},
        "deferred.isResolved": {
            "type": "Method"},
        "jQuery.undelegate": {
            "type": "Method"},
        "callbacks.fire": {
            "type": "Method"},
        "jQuery.prepend": {
            "type": "Method"},
        "jQuery.mouseenter": {
            "type": "Method"},
        "jQuery.mouseover": {
            "type": "Method"},
        "jQuery.fadeTo": {
            "type": "Method"},
        "jQuery.ajaxSetup": {
            "type": "Method"},
        "jQuery.children": {
            "type": "Method"},
        "jQuery.finish": {
            "type": "Method"},
        "jQuery.post": {
            "type": "Method"},
        "jQuery.ajaxStop": {
            "type": "Method"},
        "jQuery.position": {
            "type": "Method"},
        "jQuery.mouseleave": {
            "type": "Method"},
        "jQuery.delay": {
            "type": "Method"},
        "jQuery.isFunction": {
            "type": "Method"},
        "jQuery.ready": {
            "type": "Method"},
        "jQuery.triggerHandler": {
            "type": "Method"},
        "event.stopPropagation": {
            "type": "Method"},
        "jQuery.is": {
            "type": "Method"},
        "jQuery.removeProp": {
            "type": "Method"},
        "deferred.notify": {
            "type": "Method"},
        "jQuery.click": {
            "type": "Method"},
        "jQuery.isPlainObject": {
            "type": "Method"},
        "event.isDefaultPrevented": {
            "type": "Method"},
        "jQuery.hover": {
            "type": "Method"},
        "jQuery.map": [
            {
                "type": "Method"},
            {
                "type": "Method"}],
        "jQuery.ajaxComplete": {
            "type": "Method"},
        "jQuery.prependTo": {
            "type": "Method"},
        "jQuery.parent": {
            "type": "Method"},
        "jQuery.insertBefore": {
            "type": "Method"},
        "deferred.resolve": {
            "type": "Method"},
        "jQuery.prevAll": {
            "type": "Method"},
        "jQuery.dequeue": [
            {
                "type": "Method"},
            {
                "type": "Method"}],
        "jQuery.attr": {
            "type": "Method"},
        "jQuery.replaceAll": {
            "type": "Method"},
        "event.timeStamp": {
            "type": "EventObject"},
        "jQuery.closest": {
            "type": "Method"},
        "jQuery.off": {
            "type": "Method"},
        "jQuery.slideDown": {
            "type": "Method"},
        "jQuery.filter": {
            "type": "Method"},
        "jQuery.serializeArray": {
            "type": "Method"},
        "jQuery.replaceWith": {
            "type": "Method"},
        "jQuery.param": {
            "type": "Method"},
        "event.pageX": {
            "type": "EventObject"},
        "jQuery.size": {
            "type": "Method"},
        "jQuery.submit": {
            "type": "Method"},
        "event.pageY": {
            "type": "EventObject"},
        "deferred.always": {
            "type": "Method"},
        "jQuery.sub": {
            "type": "Method"},
        "jQuery.find": {
            "type": "Method"},
        "jQuery.focus": {
            "type": "Method"},
        "jQuery.wrapInner": {
            "type": "Method"},
        "callbacks.has": {
            "type": "Method"},
        "jQuery.prevUntil": {
            "type": "Method"},
        "jQuery.unwrap": {
            "type": "Method"},
        "event.data": {
            "type": "EventObject"},
        "jQuery.proxy": {
            "type": "Method"},
        "jQuery.siblings": {
            "type": "Method"},
        "callbacks.disabled": {
            "type": "Method"},
        "jQuery.slideToggle": {
            "type": "Method"}}}
