{
    "underscore": {
        "last": {
            "type": "Method"},
        "throttle": {
            "type": "Method"},
        "isBoolean": {
            "type": "Method"},
        "contains": {
            "type": "Method"},
        "indexOf": {
            "type": "Method"},
        "pluck": {
            "type": "Method"},
        "where": {
            "type": "Method"},
        "every": {
            "type": "Method"},
        "isNumber": {
            "type": "Method"},
        "has": {
            "type": "Method"},
        "after": {
            "type": "Method"},
        "isEmpty": {
            "type": "Method"},
        "defaults": {
            "type": "Method"},
        "compact": {
            "type": "Method"},
        "values": {
            "type": "Method"},
        "bindAll": {
            "type": "Method"},
        "countBy": {
            "type": "Method"},
        "initial": {
            "type": "Method"},
        "value": {
            "type": "Method"},
        "noConflict": {
            "type": "Method"},
        "compose": {
            "type": "Method"},
        "sortedIndex": {
            "type": "Method"},
        "template": {
            "type": "Method"},
        "clone": {
            "type": "Method"},
        "wrap": {
            "type": "Method"},
        "pairs": {
            "type": "Method"},
        "once": {
            "type": "Method"},
        "isUndefined": {
            "type": "Method"},
        "isObject": {
            "type": "Method"},
        "indexBy": {
            "type": "Method"},
        "isFunction": {
            "type": "Method"},
        "random": {
            "type": "Method"},
        "lastIndexOf": {
            "type": "Method"},
        "partial": {
            "type": "Method"},
        "without": {
            "type": "Method"},
        "reduce": {
            "type": "Method"},
        "size": {
            "type": "Method"},
        "groupBy": {
            "type": "Method"},
        "difference": {
            "type": "Method"},
        "isFinite": {
            "type": "Method"},
        "sortBy": {
            "type": "Method"},
        "isEqual": {
            "type": "Method"},
        "memoize": {
            "type": "Method"},
        "isNaN": {
            "type": "Method"},
        "each": {
            "type": "Method"},
        "rest": {
            "type": "Method"},
        "delay": {
            "type": "Method"},
        "tap": {
            "type": "Method"},
        "isArray": {
            "type": "Method"},
        "some": {
            "type": "Method"},
        "filter": {
            "type": "Method"},
        "result": {
            "type": "Method"},
        "isNull": {
            "type": "Method"},
        "reject": {
            "type": "Method"},
        "range": {
            "type": "Method"},
        "reduceRight": {
            "type": "Method"},
        "findWhere": {
            "type": "Method"},
        "object": {
            "type": "Method"},
        "escape": {
            "type": "Method"},
        "uniqueId": {
            "type": "Method"},
        "invert": {
            "type": "Method"},
        "identity": {
            "type": "Method"},
        "isElement": {
            "type": "Method"},
        "defer": {
            "type": "Method"},
        "flatten": {
            "type": "Method"},
        "times": {
            "type": "Method"},
        "union": {
            "type": "Method"},
        "map": {
            "type": "Method"},
        "mixin": {
            "type": "Method"},
        "pick": {
            "type": "Method"},
        "unescape": {
            "type": "Method"},
        "find": {
            "type": "Method"},
        "sample": {
            "type": "Method"},
        "min": {
            "type": "Method"},
        "functions": {
            "type": "Method"},
        "intersection": {
            "type": "Method"},
        "zip": {
            "type": "Method"},
        "toArray": {
            "type": "Method"},
        "max": {
            "type": "Method"},
        "keys": {
            "type": "Method"},
        "extend": {
            "type": "Method"},
        "isRegExp": {
            "type": "Method"},
        "isDate": {
            "type": "Method"},
        "debounce": {
            "type": "Method"},
        "uniq": {
            "type": "Method"},
        "chain": {
            "type": "Method"},
        "omit": {
            "type": "Method"},
        "shuffle": {
            "type": "Method"},
        "invoke": {
            "type": "Method"},
        "isArguments": {
            "type": "Method"},
        "first": {
            "type": "Method"},
        "bind": {
            "type": "Method"},
        "isString": {
            "type": "Method"}}}
